joint_number: 20
joint0_rigid1_length: 0.0
joint0_rigid2_length: 0.0
joint1_rigid1_length: 0.0
joint1_rigid2_length: 0.0
joint2_rigid1_length: 0.0
joint2_rigid2_length: 0.0
joint3_rigid1_length: 0.0
joint3_rigid2_length: 0.0
joint4_rigid1_length: 0.0
joint4_rigid2_length: 0.0
joint5_rigid1_length: 0.0
joint5_rigid2_length: 0.0
joint6_rigid1_length: 0.0
joint6_rigid2_length: 0.0
joint7_rigid1_length: 0.0
joint7_rigid2_length: 0.0
joint8_rigid1_length: 0.0
joint8_rigid2_length: 0.0
joint9_rigid1_length: 0.0
joint9_rigid2_length: 0.0
joint10_rigid1_length: 0.0
joint10_rigid2_length: 0.0
joint11_rigid1_length: 0.0
joint11_rigid2_length: 0.0
joint12_rigid1_length: 0.0
joint12_rigid2_length: 0.0
joint13_rigid1_length: 0.0
joint13_rigid2_length: 0.0
joint14_rigid1_length: 0.0
joint14_rigid2_length: 0.0
joint15_rigid1_length: 0.0
joint15_rigid2_length: 0.0
joint16_rigid1_length: 0.0
joint16_rigid2_length: 0.0
joint17_rigid1_length: 0.0
joint17_rigid2_length: 0.0
joint18_rigid1_length: 0.0
joint18_rigid2_length: 0.0
joint19_rigid1_length: 0.0
joint19_rigid2_length: 0.0

joint0_continuum_length: 100.0
joint1_continuum_length: 100.0
joint2_continuum_length: 100.0
joint3_continuum_length: 100.0
joint4_continuum_length: 100.0
joint5_continuum_length: 100.0
joint6_continuum_length: 100.0
joint7_continuum_length: 100.0
joint8_continuum_length: 100.0
joint9_continuum_length: 100.0
joint10_continuum_length: 100.0
joint11_continuum_length: 100.0
joint12_continuum_length: 100.0
joint13_continuum_length: 100.0
joint14_continuum_length: 100.0
joint15_continuum_length: 100.0
joint16_continuum_length: 100.0
joint17_continuum_length: 100.0
joint18_continuum_length: 100.0
joint19_continuum_length: 100.0

bspline_interval_point1_x: -7.5
bspline_interval_point1_y: 190.5
bspline_interval_point1_z: 46.6
bspline_interval_point2_x: -12.4
bspline_interval_point2_y: 299.4
bspline_interval_point2_z: 95.5 
bspline_interval_point3_x: 40.6
bspline_interval_point3_y: 438.4
bspline_interval_point3_z: 154.1
bspline_interval_point4_x: 120.4
bspline_interval_point4_y: 592.1
bspline_interval_point4_z: 206.0
bspline_interval_point5_x: 119.7
bspline_interval_point5_y: 772.6
bspline_interval_point5_z: 274.5
bspline_interval_point6_x: 84.6
bspline_interval_point6_y: 905.0
bspline_interval_point6_z: 295.3
bspline_interval_point7_x: 55.1
bspline_interval_point7_y: 1009.2
bspline_interval_point7_z: 262.7
bspline_interval_point8_x: 43.2
bspline_interval_point8_y: 1101.8
bspline_interval_point8_z: 156.6
bspline_interval_point9_x: 29.6
bspline_interval_point9_y: 1314.5
bspline_interval_point9_z: 77.9
bspline_interval_point10_x: 16.3
bspline_interval_point10_y: 1805.5
bspline_interval_point10_z: 38.1
bspline_interval_point11_x: 0.0
bspline_interval_point11_y: 2300.0
bspline_interval_point11_z: 0.0

bspline_start_vel_x: 0.0
bspline_start_vel_y: 4.0
bspline_start_vel_z: 0.0
bspline_end_vel_x: 0.0
bspline_end_vel_y: 3.0
bspline_end_vel_z: 0.0
bspline_start_acc_x: 0.0
bspline_start_acc_y: 0.0
bspline_start_acc_z: 0.0
bspline_end_acc_x: 0.0
bspline_end_acc_y: 0.0
bspline_end_acc_z: 0.0

path_follow_nanotime_interval: 500000000
sample_interval: 1.0
bone_sample_interval: 1.0
experience_type: 2
base_path_point_start_x: 0.0
base_path_point_start_y: 0.0
base_path_point_start_z: 0.0
base_path_point_end_x: 0.0
base_path_point_end_y: 2100.0
base_path_point_end_z: 0.0
arc_path_alpha: 0.0
arc_path_theta: 180.0
post_line_path_length: 2100.0
# the real base travel could use the init pose and end pose to confirm;
base_start_point_x: 0.0
base_start_point_y: 1.0
base_start_point_z: 0.0
base_end_point_x: 0.0
base_end_point_y: 2099.0
base_end_point_z: 0.0
base_z_axis_x: 0.0
base_z_axis_y: 1.0
base_z_axis_z: 0.0
base_y_axis_x: 1.0
base_y_axis_y: 0.0
base_y_axis_z: 0.0
start_track_path_point_id: 1
base_tolerance_deviation: 1.0
base_tolerance_angle_deviation: 4.0
# this is the minimum value of remaining length over the length of the robot
safe_path_length_redundance: 200.0
min_arc_radius: 450.0
max_arc_radius: 450.0
# 位置误差权重
weight_position: 0.029412
# weight_position: 1.0
# 方向误差权重
weight_direction: 0.970588
# weight_direction: 0.0
# the size of base box model for visualization
base_box_size_x: 100.0
base_box_size_y: 100.0
base_box_size_z: 300.0
cdcr_point_size_x: 8.0
cdcr_point_size_y: 8.0
cdcr_point_size_z: 8.0
cdcr_plat_size_x: 80.0
cdcr_plat_size_y: 80.0
cdcr_plat_size_z: 8.0
base_box_color_r: 0.1
base_box_color_g: 0.05
base_box_color_b: 0.05
base_box_color_a: 1.0
cdcr_point_color_r: 0.0
cdcr_point_color_g: 0.0
cdcr_point_color_b: 1.0
cdcr_point_color_a: 1.0
cdcr_plat_color_r: 0.9
cdcr_plat_color_g: 0.2
cdcr_plat_color_b: 0.0
cdcr_plat_color_a: 1.0

path_point_scale: 3.0
path_point_color_r: 0.3
path_point_color_g: 0.4
path_point_color_b: 0.41
path_point_color_a: 1.0

deviation_marker_scale_x: 1.0
deviation_marker_scale_y: 0.0
deviation_marker_scale_z: 0.0
deviation_marker_zoom_factor: 1.0
sleep_nano_time: 0

alpha_lower_bound: -180.0
alpha_upper_bound: 180.0
theta_lower_bound: -90.0
theta_upper_bound: 90.0

arc_path_radius_step: 4.0

visualization_flag: 1

time_interval: 30.0

theta_change_thresh: 4.0

cylinder1_scale_x: 150.0
cylinder1_scale_y: 150.0
cylinder1_scale_z: 600.0
cylinder2_scale_x: 200.0
cylinder2_scale_y: 200.0
cylinder2_scale_z: 600.0

cylinder1_color_r: 0.6
cylinder1_color_g: 0.6
cylinder1_color_b: 0.6
cylinder2_color_r: 0.6
cylinder2_color_g: 0.6
cylinder2_color_b: 0.6

cylinder1_position_x: 0.0
cylinder1_position_y: 2730.0
cylinder1_position_z: 70.0
cylinder2_position_x: 0.0
cylinder2_position_y: 3010.0
cylinder2_position_z: 140.0

cylinder1_axis_x: 0.0
cylinder1_axis_y: 0.0
cylinder1_axis_z: 1.0
cylinder2_axis_x: 1.0
cylinder2_axis_y: 0.0
cylinder2_axis_z: 0.0

hole_scale_x: 120.0
hole_scale_z: 120.0

hole1_position_x: 15.0
hole1_position_y: 2468.0
hole1_position_z: 128.0

hole2_position_x: 37.0
hole2_position_y: 3307.0
hole2_position_z: 117.0

board_left_right_scale_x: 600.0
board_left_right_scale_y: 5.0
board_left_right_scale_z: 600.0
board_left_right_color_r: 0.6
board_left_right_color_g: 0.6
board_left_right_color_b: 0.6

board_up_down_scale_x: 600.0
board_up_down_scale_y: 5.0
board_up_down_scale_z: 600.0
board_up_down_color_r: 0.6
board_up_down_color_g: 0.6
board_up_down_color_b: 0.6

flag_visualize_b_spline_marker: 1

# the end index at the path point list

# norm_vector_circle1_x: 1.0
# norm_vector_circle1_y: 0.0
# norm_vector_circle1_z: 0.0
# radius1: 200
# norm_vector_circle2_x: 0.0
# norm_vector_circle2_y: -1.0
# norm_vector_circle2_z: 0.0
# radius2: 200
