joint_number: 20
joint0_rigid1_length: 0.0
joint0_rigid2_length: 0.0
joint1_rigid1_length: 0.0
joint1_rigid2_length: 0.0
joint2_rigid1_length: 0.0
joint2_rigid2_length: 0.0
joint3_rigid1_length: 0.0
joint3_rigid2_length: 0.0
joint4_rigid1_length: 0.0
joint4_rigid2_length: 0.0
joint5_rigid1_length: 0.0
joint5_rigid2_length: 0.0
joint6_rigid1_length: 0.0
joint6_rigid2_length: 0.0
joint7_rigid1_length: 0.0
joint7_rigid2_length: 0.0
joint8_rigid1_length: 0.0
joint8_rigid2_length: 0.0
joint9_rigid1_length: 0.0
joint9_rigid2_length: 0.0
joint10_rigid1_length: 0.0
joint10_rigid2_length: 0.0
joint11_rigid1_length: 0.0
joint11_rigid2_length: 0.0
joint12_rigid1_length: 0.0
joint12_rigid2_length: 0.0
joint13_rigid1_length: 0.0
joint13_rigid2_length: 0.0
joint14_rigid1_length: 0.0
joint14_rigid2_length: 0.0
joint15_rigid1_length: 0.0
joint15_rigid2_length: 0.0
joint16_rigid1_length: 0.0
joint16_rigid2_length: 0.0
joint17_rigid1_length: 0.0
joint17_rigid2_length: 0.0
joint18_rigid1_length: 0.0
joint18_rigid2_length: 0.0
joint19_rigid1_length: 0.0
joint19_rigid2_length: 0.0

joint0_continuum_length: 100.0
joint1_continuum_length: 100.0
joint2_continuum_length: 100.0
joint3_continuum_length: 100.0
joint4_continuum_length: 100.0
joint5_continuum_length: 100.0
joint6_continuum_length: 100.0
joint7_continuum_length: 100.0
joint8_continuum_length: 100.0
joint9_continuum_length: 100.0
joint10_continuum_length: 100.0
joint11_continuum_length: 100.0
joint12_continuum_length: 100.0
joint13_continuum_length: 100.0
joint14_continuum_length: 100.0
joint15_continuum_length: 100.0
joint16_continuum_length: 100.0
joint17_continuum_length: 100.0
joint18_continuum_length: 100.0
joint19_continuum_length: 100.0

path_follow_nanotime_interval: 500000000
sample_interval: 1.0
bone_sample_interval: 1.0
experience_type: 1
base_path_point_start_x: 0.0
base_path_point_start_y: 0.0
base_path_point_start_z: 0.0
base_path_point_end_x: 0.0
base_path_point_end_y: 2100.0
base_path_point_end_z: 0.0
arc_path_alpha: 0.0
arc_path_theta: 180.0
post_line_path_length: 2100.0
# the real base travel could use the init pose and end pose to confirm;
base_start_point_x: 0.0
base_start_point_y: 1.0
base_start_point_z: 0.0
base_end_point_x: 0.0
base_end_point_y: 2099.0
base_end_point_z: 0.0
base_z_axis_x: 0.0
base_z_axis_y: 1.0
base_z_axis_z: 0.0
base_y_axis_x: 1.0
base_y_axis_y: 0.0
base_y_axis_z: 0.0
start_track_path_point_id: 1
base_tolerance_deviation: 1.0
base_tolerance_angle_deviation: 4.0
# this is the minimum value of remaining length over the length of the robot
safe_path_length_redundance: 200.0
min_arc_radius: 60.0
max_arc_radius: 260.0
# 位置误差权重
weight_position: 0.029412
# 方向误差权重
weight_direction: 0.970588
# the size of base box model for visualization
base_box_size_x: 100.0
base_box_size_y: 100.0
base_box_size_z: 300.0
cdcr_point_size_x: 8.0
cdcr_point_size_y: 8.0
cdcr_point_size_z: 8.0
cdcr_plat_size_x: 80.0
cdcr_plat_size_y: 80.0
cdcr_plat_size_z: 8.0
base_box_color_r: 0.1
base_box_color_g: 0.05
base_box_color_b: 0.05
base_box_color_a: 1.0
cdcr_point_color_r: 0.0
cdcr_point_color_g: 0.0
cdcr_point_color_b: 1.0
cdcr_point_color_a: 1.0
cdcr_plat_color_r: 0.9
cdcr_plat_color_g: 0.2
cdcr_plat_color_b: 0.0
cdcr_plat_color_a: 1.0

path_point_scale: 1.5
path_point_color_r: 0.31
path_point_color_g: 0.4
path_point_color_b: 0.41
path_point_color_a: 1.0

deviation_marker_scale_x: 1.0
deviation_marker_scale_y: 0.0
deviation_marker_scale_z: 0.0
deviation_marker_zoom_factor: 1.0
sleep_nano_time: 0

alpha_lower_bound: -180.0
alpha_upper_bound: 180.0
theta_lower_bound: -90.0
theta_upper_bound: 90.0

arc_path_radius_step: 4.0

visualization_flag: 1

# the end index at the path point list

# norm_vector_circle1_x: 1.0
# norm_vector_circle1_y: 0.0
# norm_vector_circle1_z: 0.0
# radius1: 200
# norm_vector_circle2_x: 0.0
# norm_vector_circle2_y: -1.0
# norm_vector_circle2_z: 0.0
# radius2: 200
